Addressing WGLC and YANGDOC review comments.
ietf-ccamp-wg/draft-ietf-ccamp-layer0-types pull request #15
Opened 2020-12-14 19:36 UTC by agva123

Addressing WGLC and YANGDOC review comments.

2020-12-15 15:01 UTC, italobusi requested changes

2020-12-15 15:01 UTC, italobusi commented on ietf-layer0-types.yang
> +	   frequency.
```suggestion
      "The given value 'N' is used to determine the nominal central
       frequency.
```

Please fix all the tabs

2020-12-15 15:01 UTC, italobusi commented on ietf-layer0-types.yang
>         where 'channel-spacing' is defined by the dwdm-ch-spc-type.";
Proposed rephrase to make it nicer to read:

```
       The nominal central frequency, 'f' is defined by:

         f = 193100.000 GHz + N x channel-spacing (measured in GHz)

       where 193100.000 GHz (193.100000 THz) is the ITU-T 'anchor 
       frequency' for transmission over the C band; and

       where  'channel-spacing' is defined by the dwdm-ch-spc-type.";
```

2020-12-15 15:01 UTC, italobusi commented on ietf-layer0-types.yang
> +           equal to minimum slot width.";
If not specified, the maximum slot width is equal to minimum slot width.

2020-12-30 03:10 UTC, haomianzheng approved these changes

2020-12-30 03:11 UTC, merged